call_parentheses = "None"
collapse_simple_statement = "Always"
column_width = 80
indent_width = 3
indent_type = "Tabs"
line_endings = "Unix"
quote_style = "AutoPreferDouble"
syntax = "Lua54"

[sort_requires]
enabled = true
